language: python

dist: xenial   # required for Python >= 3.7
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

branches:
    only:
    - master
    - devel

install: pip install tox-travis

script: tox

after_script:
- if [ $TOXENV == "cov" ]; then
    pip install coveralls;
    coveralls;
  fi
