version: 2

jobs:
  toxify:
      docker:
        - image: python:3.6
        - image: python:3.7

      steps:
        - checkout
        - run: pip install tox && tox

workflows:
  version: 2

  nmap-wrapper:
    jobs:
      - toxify
