version: 2

jobs:
  toxify:
      docker:
        - image: python:3.6
        - image: python:3.7
        - image: python:3.8

      steps:
        - checkout
        - run: pip install tox && tox

workflows:
  version: 2

  nmap-wrapper:
    jobs:
      - toxify
